export function slugify(value) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const CATEGORIES = [
  { id: "all", label: "All Products", icon: "HiSquares2X2" },
  {
    id: "switches-accessories",
    label: "Switches & Accessories",
    icon: "HiAdjustmentsHorizontal",
  },
  {
    id: "electrical-wires-cables",
    label: "Electrical Wires & Cables",
    icon: "HiBolt",
  },
  { id: "mcbs-protection", label: "MCBs & Protection", icon: "HiShieldCheck" },
  { id: "lighting", label: "Lighting", icon: "HiLightBulb" },
  { id: "fans", label: "Fans", icon: "HiArrowPath" },
  { id: "water-pumps-heaters", label: "Water Pumps & Heaters", icon: "HiFire" },
  { id: "pipes-fittings", label: "Pipes and Fittings", icon: "HiCube" },
  {
    id: "industrial-electrical-products",
    label: "Industrial Electrical Products",
    icon: "HiBuildingOffice2",
  },
  {
    id: "electrical-tools-accessories",
    label: "Electrical Tools & Accessories",
    icon: "HiWrenchScrewdriver",
  },
  {
    id: "earthing-materials",
    label: "Earthing Materials",
    icon: "HiGlobeAlt",
  },
  {
    id: "home-appliance",
    label: "Home Appliance",
    icon: "HiHome",
  },
  {
    id: "aquagard",
    label: "Aquagard",
    icon: "HiBeaker",
  },
];

export const CATEGORY_SPECS = {
  fans: [
    "Sweep Size (mm)",
    "Power Consumption (Watts)",
    "Air Delivery (CMM)",
    "RPM",
    "Number of Blades",
    "Voltage",
    "Frequency",
    "Motor Type",
    "Warranty",
    "Color",
  ],
  "switches-accessories": [
    "Current Rating (A)",
    "Voltage (V)",
    "Number of Modules",
    "Material",
    "Finish",
    "Indicator",
    "Fire Resistant",
    "ISI Certified",
    "Warranty",
  ],
  "electrical-wires-cables": [
    "Size (Sq mm)",
    "Length",
    "Conductor Material",
    "Insulation Type",
    "Voltage Grade",
    "FR / FRLS / HRFR",
    "Number of Cores",
    "Color",
    "ISI Mark",
    "Application",
  ],
  lighting: [
    "Wattage",
    "Voltage",
    "Lumens",
    "Color Temperature (K)",
    "Beam Angle",
    "CRI",
    "IP Rating",
    "Lifespan",
    "Driver Type",
    "Warranty",
  ],
  "mcbs-protection": [
    "Current Rating",
    "Pole",
    "Breaking Capacity",
    "Curve Type",
    "Voltage",
    "Frequency",
    "Mounting Type",
    "ISI Certified",
  ],
  "water-pumps-heaters": [
    "HP",
    "Head",
    "Flow Rate",
    "Voltage",
    "Power",
    "Pipe Size",
    "Motor Type",
    "Warranty",
  ],
  "pipes-fittings": [
    "Material",
    "Size",
    "Pressure Rating",
    "Length",
    "Thickness",
    "Color",
    "Application",
  ],
  "home-appliance": [
    "Power",
    "Voltage",
    "Capacity",
    "Dimensions",
    "Weight",
    "Warranty",
    "Energy Rating",
  ],
  "industrial-electrical-products": [
    "Model",
    "Input Voltage",
    "Output Voltage",
    "Current",
    "Phase",
    "Frequency",
    "Mounting",
    "IP Rating",
  ],
  "electrical-tools-accessories": [
    "Power",
    "Battery",
    "Speed",
    "Torque",
    "Weight",
    "Warranty",
  ],
  "earthing-materials": [
    "Material",
    "Length",
    "Diameter",
    "Coating",
    "Resistance",
    "Standard",
  ],
  aquagard: [
    "Capacity",
    "Purification Technology",
    "Storage",
    "Power",
    "Filter Type",
    "Recovery Rate",
    "Warranty",
  ],
};

const RAW_PRODUCTS = [
  // ============================================================
  // Switches & Accessories
  // ============================================================
  {
    id: 1,
    name: "arcus-switches",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Best Seller",
    price: 249,
    originalPrice: 329,
    discount: 24,
    stock: 140,
    rating: 4.8,
    reviews: 2345,
    image: "/myrahswitches/arcus-switches.webp",
    badge: "Best Seller",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: [
          "/myrahswitches/arcus-switches.webp",
          "/myrahswitches/arcus-switches.webp",
        ],
        stock: 140,
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: [
          "/myrahswitches/arcus-switches.webp",
          "/myrahswitches/arcus-switches.webp",
        ],
        price: 269,
        originalPrice: 349,
        stock: 6,
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/myrahswitches/arcus-switches.webp",
          "/myrahswitches/arcus-switches.webp",
        ],
        price: 279,
        originalPrice: 359,
        stock: 2,
        specifications: {
          Finish: "Matte Black",
        },
      },
    ],
    description:
      "Premium quality modular switch with LED indicator, designed for durability and safety in modern homes.",
    features: [
      "20A current rating",
      "LED indicator light",
      "Fire-resistant polycarbonate body",
      "Easy snap-fit installation",
      "5-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "20A",
      "Voltage (V)": "240V",
      "Number of Modules": "1 Module",
      Material: "Polycarbonate",
      Finish: "Matte",
      Indicator: "LED Indicator",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "5 Years",
    },
  },
  {
    id: 2,
    name: "Domia switches",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/myrahswitches/Domia switches.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/myrahswitches/Domia switches.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/myrahswitches/Domia switches.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "6A",
      "Voltage (V)": "240V",
      "Number of Modules": "1 Module",
      Material: "Polycarbonate",
      Finish: "Soft-touch Rocker",
      Indicator: "No",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "10 Years",
    },
  },
  {
    id: 3,
    name: "fiana switches",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/myrahswitches/fiana switches.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/myrahswitches/fiana switches.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/myrahswitches/fiana switches.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "6A",
      "Voltage (V)": "240V",
      "Number of Modules": "1 Module",
      Material: "Polycarbonate",
      Finish: "Soft-touch Rocker",
      Indicator: "No",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "10 Years",
    },
  },
  {
    id: 4,
    name: "myrah-brilliant-shine switches",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/myrahswitches/myrah-brilliant-shine switches.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/myrahswitches/myrah-brilliant-shine switches.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/myrahswitches/myrah-brilliant-shine switches.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "6A",
      "Voltage (V)": "240V",
      "Number of Modules": "1 Module",
      Material: "Polycarbonate",
      Finish: "Soft-touch Rocker",
      Indicator: "No",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "10 Years",
    },
  },
  {
    id: 5,
    name: "petra extension board",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/myrahswitches/petra extension board.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/myrahswitches/petra extension board.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/myrahswitches/petra extension board.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "16A",
      "Voltage (V)": "240V",
      "Number of Modules": "6 Modules",
      Material: "Polycarbonate",
      Finish: "Matte",
      Indicator: "No",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "1 Year",
    },
  },
  {
    id: 6,
    name: "trivo switches",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Myrah",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/myrahswitches/trivo switches.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/myrahswitches/trivo switches.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/myrahswitches/trivo switches.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
    specifications: {
      "Current Rating (A)": "6A",
      "Voltage (V)": "240V",
      "Number of Modules": "1 Module",
      Material: "Polycarbonate",
      Finish: "Soft-touch Rocker",
      Indicator: "No",
      "Fire Resistant": "Yes",
      "ISI Certified": "Yes",
      Warranty: "10 Years",
    },
  },

  // ============================================================
  // Electrical Wires & Cables
  // ============================================================
  {
    id: 7,
    name: "Finolex FR — 1.5 Sq mm PVC Insulated Copper Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "Finolex",
    tag: "New Arrival",
    price: 1899,
    originalPrice: 2399,
    discount: 21,
    stock: 54,
    rating: 4.9,
    reviews: 1823,
    image:
      "/wiresandcables/Finolex FR — 1.5 Sq mm PVC Insulated Copper Wire (90m).webp",
    badge: "New",
    colors: [
      {
        name: "Red",
        hex: "#c0392b",
        images: [
          "/wiresandcables/Finolex FR — 1.5 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
      {
        name: "Blue",
        hex: "#2c5f8a",
        images: [
          "/wiresandcables/Finolex FR — 1.5 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/wiresandcables/Finolex FR — 1.5 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
    ],
    description:
      "Flame retardant house wire ideal for residential and commercial wiring, ensuring maximum safety.",
    features: [
      "1.5 sq mm thickness",
      "90 meters length",
      "Flame retardant (FR) grade",
      "High conductivity copper",
      "ISI marked",
    ],
    specifications: {
      "Size (Sq mm)": "1.5 Sq mm",
      Length: "90 Meters",
      "Conductor Material": "Copper",
      "Insulation Type": "PVC",
      "Voltage Grade": "1100V",
      "FR / FRLS / HRFR": "FR",
      "Number of Cores": "Single Core",
      Color: "Red / Blue / Black",
      "ISI Mark": "Yes",
      Application: "Residential & Commercial Wiring",
    },
  },
  {
    id: 8,
    name: "Havells Life Line Plus S3 — 1.5 Sq mm PVC HRFR Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "Havells",
    tag: "Best Seller",
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    stock: 38,
    rating: 4.6,
    reviews: 1567,
    image:
      "/wiresandcables/Havells Life Line Plus S3 — 1.5 Sq mm PVC HRFR Wire (90m).webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Red",
        hex: "#c0392b",
        images: [
          "/wiresandcables/Havells Life Line Plus S3 — 1.5 Sq mm PVC HRFR Wire (90m).webp",
        ],
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/wiresandcables/Havells Life Line Plus S3 — 1.5 Sq mm PVC HRFR Wire (90m).webp",
        ],
      },
    ],
    description:
      "Multistrand FR-LSH cable with silicon-treated insulation for higher fire and heat resistance.",
    features: [
      "2.5 sq mm thickness",
      "90 meters length",
      "Silicon FR-LSH insulation",
      "High flexibility multistrand copper",
      "ISI marked",
    ],
    specifications: {
      "Size (Sq mm)": "1.5 Sq mm",
      Length: "90 Meters",
      "Conductor Material": "Multistrand Copper",
      "Insulation Type": "Silicon FR-LSH PVC",
      "Voltage Grade": "1100V",
      "FR / FRLS / HRFR": "HRFR",
      "Number of Cores": "Single Core",
      Color: "Red / Black",
      "ISI Mark": "Yes",
      Application: "Residential & Commercial Wiring",
    },
  },
  {
    id: 9,
    name: "KEI Homecab FR — 1 Sq mm PVC Insulated Copper Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "KEI",
    tag: "Best Seller",
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    stock: 38,
    rating: 4.6,
    reviews: 1567,
    image:
      "/wiresandcables/KEI Homecab FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Red",
        hex: "#c0392b",
        images: [
          "/wiresandcables/KEI Homecab FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/wiresandcables/KEI Homecab FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
    ],
    description:
      "Multistrand FR-LSH cable with silicon-treated insulation for higher fire and heat resistance.",
    features: [
      "2.5 sq mm thickness",
      "90 meters length",
      "Silicon FR-LSH insulation",
      "High flexibility multistrand copper",
      "ISI marked",
    ],
    specifications: {
      "Size (Sq mm)": "1 Sq mm",
      Length: "90 Meters",
      "Conductor Material": "Multistrand Copper",
      "Insulation Type": "FR-LSH PVC",
      "Voltage Grade": "1100V",
      "FR / FRLS / HRFR": "FR",
      "Number of Cores": "Single Core",
      Color: "Red / Black",
      "ISI Mark": "Yes",
      Application: "Residential & Commercial Wiring",
    },
  },
  {
    id: 10,
    name: "Polycab FR-LF — 1 Sq mm PVC Insulated Copper Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "Polycab",
    tag: "Best Seller",
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    stock: 38,
    rating: 4.6,
    reviews: 1567,
    image:
      "/wiresandcables/Polycab FR-LF — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Red",
        hex: "#c0392b",
        images: [
          "/wiresandcables/Polycab FR-LF — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/wiresandcables/Polycab FR-LF — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
    ],
    description:
      "Multistrand FR-LSH cable with silicon-treated insulation for higher fire and heat resistance.",
    features: [
      "2.5 sq mm thickness",
      "90 meters length",
      "Silicon FR-LSH insulation",
      "High flexibility multistrand copper",
      "ISI marked",
    ],
    specifications: {
      "Size (Sq mm)": "1 Sq mm",
      Length: "90 Meters",
      "Conductor Material": "Multistrand Copper",
      "Insulation Type": "FR-LSH PVC",
      "Voltage Grade": "1100V",
      "FR / FRLS / HRFR": "FR-LF",
      "Number of Cores": "Single Core",
      Color: "Red / Black",
      "ISI Mark": "Yes",
      Application: "Residential & Commercial Wiring",
    },
  },
  {
    id: 11,
    name: "RR Kabel Superex FR — 1 Sq mm PVC Insulated Copper Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "RR Kabel",
    tag: "Best Seller",
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    stock: 38,
    rating: 4.6,
    reviews: 1567,
    image:
      "/wiresandcables/RR Kabel Superex FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Red",
        hex: "#c0392b",
        images: [
          "/wiresandcables/RR Kabel Superex FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: [
          "/wiresandcables/RR Kabel Superex FR — 1 Sq mm PVC Insulated Copper Wire (90m).webp",
        ],
      },
    ],
    description:
      "Multistrand FR-LSH cable with silicon-treated insulation for higher fire and heat resistance.",
    features: [
      "2.5 sq mm thickness",
      "90 meters length",
      "Silicon FR-LSH insulation",
      "High flexibility multistrand copper",
      "ISI marked",
    ],
    specifications: {
      "Size (Sq mm)": "1 Sq mm",
      Length: "90 Meters",
      "Conductor Material": "Multistrand Copper",
      "Insulation Type": "FR-LSH PVC",
      "Voltage Grade": "1100V",
      "FR / FRLS / HRFR": "FR",
      "Number of Cores": "Single Core",
      Color: "Red / Black",
      "ISI Mark": "Yes",
      Application: "Residential & Commercial Wiring",
    },
  },

  // ============================================================
  // MCBs & Protection
  // ============================================================
  {
    id: 12,
    name: "Havells 32A Double Pole MCB",
    category: "MCBs & Protection",
    categoryId: "mcbs-protection",
    brand: "Havells",
    tag: "Popular",
    price: 349,
    originalPrice: 449,
    discount: 22,
    stock: 210,
    rating: 4.7,
    reviews: 892,
    image: "/images/productimages/p3.jpg",
    badge: "Popular",
    description:
      "Double pole miniature circuit breaker providing reliable overload and short circuit protection.",
    features: [
      "32A current rating",
      "Double pole (DP)",
      "C curve tripping",
      "10kA breaking capacity",
      "DIN rail mounting",
    ],
    specifications: {
      "Current Rating": "32A",
      Pole: "Double Pole (DP)",
      "Breaking Capacity": "10kA",
      "Curve Type": "C Curve",
      Voltage: "240V / 415V",
      Frequency: "50Hz",
      "Mounting Type": "DIN Rail",
      "ISI Certified": "Yes",
    },
  },
  {
    id: 13,
    name: "KEI 40A 4-Pole RCCB/ELCB",
    category: "MCBs & Protection",
    categoryId: "mcbs-protection",
    brand: "KEI",
    tag: "Featured",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    stock: 65,
    rating: 4.8,
    reviews: 532,
    image: "/images/productimages/p4.webp",
    badge: "Featured",
    description:
      "Residual current circuit breaker providing earth leakage protection for entire electrical circuits.",
    features: [
      "40A rated current",
      "30mA sensitivity",
      "4-pole configuration",
      "Fast tripping mechanism",
      "ISI marked",
    ],
    specifications: {
      "Current Rating": "40A",
      Pole: "4 Pole",
      "Breaking Capacity": "10kA",
      "Curve Type": "N/A (RCCB)",
      Voltage: "415V",
      Frequency: "50Hz",
      "Mounting Type": "DIN Rail",
      "ISI Certified": "Yes",
    },
  },
  {
    id: 14,
    name: "Polycab 32A DP MCB",
    category: "MCBs & Protection",
    categoryId: "mcbs-protection",
    brand: "Polycab",
    tag: "Featured",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    stock: 65,
    rating: 4.8,
    reviews: 532,
    image: "/images/productimages/p4.webp",
    badge: "Featured",
    description:
      "Residual current circuit breaker providing earth leakage protection for entire electrical circuits.",
    features: [
      "40A rated current",
      "30mA sensitivity",
      "4-pole configuration",
      "Fast tripping mechanism",
      "ISI marked",
    ],
    specifications: {
      "Current Rating": "32A",
      Pole: "Double Pole (DP)",
      "Breaking Capacity": "10kA",
      "Curve Type": "C Curve",
      Voltage: "240V / 415V",
      Frequency: "50Hz",
      "Mounting Type": "DIN Rail",
      "ISI Certified": "Yes",
    },
  },

  // ============================================================
  // Lighting
  // ============================================================
  {
    id: 15,
    name: "SHOCKINGLY BRIGHT A TYPE BULB - 120LPW",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "Best Seller",
    price: 320,
    originalPrice: 326,
    discount: 29,
    stock: 480,
    rating: 4.7,
    reviews: 4521,
    image: "/luma_pro_light/SHOCKINGLY BRIGHT A TYPE BULB - 120LPW.webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Cool Daylight",
        hex: "#eef3ff",
        images: ["/luma_pro_light/SHOCKINGLY BRIGHT A TYPE BULB - 120LPW.webp"],
      },
    ],
    description:
      "Energy-saving LED bulb twin pack with cool daylight color, perfect for home and office lighting.",
    features: [
      "120LPW power consumption",
      "6500K cool daylight",
      "1200 lumens brightness",
      "25,000 hours lifespan",
      "BIS certified",
    ],
    specifications: {
      Wattage: "10W",
      Voltage: "140-300V",
      Lumens: "1200 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "360°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver",
      Warranty: "2 Years",
    },
  },
  {
    id: 16,
    name: "SHOCKINGLY BRIGHT BATTEN - 120LPW",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 350,
    originalPrice: 354,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/luma_pro_light/SHOCKINGLY BRIGHT BATTEN - 120LPW.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/luma_pro_light/SHOCKINGLY BRIGHT BATTEN - 120LPW.webp"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "20W",
      Voltage: "140-300V",
      Lumens: "1800 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "120°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver",
      Warranty: "2 Years",
    },
  },
  {
    id: 17,
    name: "SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 850,
    originalPrice: 870,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image:
      "/luma_pro_light/SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)_1.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: [
          "/luma_pro_light/SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)_1.webp",
        ],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "18W",
      Voltage: "140-300V",
      Lumens: "1800 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "120°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver",
      Warranty: "2 Years",
    },
  },
  {
    id: 18,
    name: "SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)_2",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 1000,
    originalPrice: 1101,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image:
      "/luma_pro_light/SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)_2.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: [
          "/luma_pro_light/SHOCKINGLY BRIGHT PANEL - 120LMW (WITH CUTOUT ADJUSTMENT)_2.webp",
        ],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "22W",
      Voltage: "140-300V",
      Lumens: "2200 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "120°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver",
      Warranty: "2 Years",
    },
  },
  {
    id: 19,
    name: "SHOCKINGLY BRIGHT T TYPE BULB - 120LPW",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 350,
    originalPrice: 370,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/luma_pro_light/SHOCKINGLY BRIGHT T TYPE BULB - 120LPW.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/luma_pro_light/SHOCKINGLY BRIGHT T TYPE BULB - 120LPW.webp"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "12W",
      Voltage: "140-300V",
      Lumens: "1400 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "200°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver",
      Warranty: "2 Years",
    },
  },
  {
    id: 20,
    name: "SLIM PANEL (THERMO PLASTIC) - EDGE LIT (INBUILT DRIVER) ROUND",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 600,
    originalPrice: 650,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image:
      "/luma_pro_light/SLIM PANEL (THERMO PLASTIC) - EDGE LIT (INBUILT DRIVER) ROUND.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: [
          "/luma_pro_light/SLIM PANEL (THERMO PLASTIC) - EDGE LIT (INBUILT DRIVER) ROUND.webp",
        ],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "15W",
      Voltage: "140-300V",
      Lumens: "1650 lm",
      "Color Temperature (K)": "6500K",
      "Beam Angle": "120°",
      CRI: ">80",
      "IP Rating": "IP20",
      Lifespan: "25,000 Hours",
      "Driver Type": "Inbuilt Driver (Edge Lit)",
      Warranty: "2 Years",
    },
  },
  {
    id: 21,
    name: "STRIP LIGHT 12VDC - 120 & 240 LEDMTR. (5 MTRROLL)",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 850,
    originalPrice: 870,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image:
      "/luma_pro_light/STRIP LIGHT 12VDC - 120 & 240 LEDMTR. (5 MTRROLL).webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: [
          "/luma_pro_light/STRIP LIGHT 12VDC - 120 & 240 LEDMTR. (5 MTRROLL).webp",
        ],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
    specifications: {
      Wattage: "9.6W/m",
      Voltage: "12V DC",
      Lumens: "120-240 lm/m",
      "Color Temperature (K)": "6500K / 3000K",
      "Beam Angle": "120°",
      CRI: ">80",
      "IP Rating": "IP65",
      Lifespan: "20,000 Hours",
      "Driver Type": "External Driver Required",
      Warranty: "1 Year",
    },
  },
  {
    id: 22,
    name: "NIGHT LAMP",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 65,
    originalPrice: 70,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/luma_pro_light/NIGHT LAMP.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/luma_pro_light/NIGHT LAMP.webp"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
  },
  {
    id: 23,
    name: "ROPE LIGHT - IP65 (50 MTRROLL)",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 65,
    originalPrice: 70,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/luma_pro_light/ROPE LIGHT - IP65 (50 MTRROLL).webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/luma_pro_light/ROPE LIGHT - IP65 (50 MTRROLL).webp"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
  },
  {
    id: 24,
    name: "RIMLESS SURFACE DOWN LIGHT (THERMO PLASTIC)- (DOB) SQUARE",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 550,
    originalPrice: 560,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image:
      "/luma_pro_light/RIMLESS SURFACE DOWN LIGHT (THERMO PLASTIC)- (DOB) SQUARE.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: [
          "/luma_pro_light/RIMLESS SURFACE DOWN LIGHT (THERMO PLASTIC)- (DOB) SQUARE.webp",
        ],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
  },
  {
    id: 25,
    name: "E-NOVA COB DOWN LIGHT EXTERNAL DRIVER",
    category: "Lighting",
    categoryId: "lighting",
    brand: "GreatWhite",
    tag: "New Arrival",
    price: 65,
    originalPrice: 70,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/luma_pro_light/E-NOVA COB DOWN LIGHT EXTERNAL DRIVER.webp",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/luma_pro_light/E-NOVA COB DOWN LIGHT EXTERNAL DRIVER.webp"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "120LPW power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
    ],
  },

  // ============================================================
  // Fans
  // ============================================================
  {
    id: 26,
    name: "Emperion Magna",
    category: "Fans",
    categoryId: "fans",
    brand: "Atomberg",
    tag: "Popular",
    price: 17999,
    originalPrice: 25999,
    discount: 23,
    stock: 14,
    rating: 4.7,
    reviews: 987,
    image: "/Fan/emperion_magna_1280_plis_amber_lightteak.webp",
    badge: "Popular",
    colors: [
      {
        name: "Amberlight Teak",
        hex: "#6b4426",
        images: [
          "/Fan/emperion_magna_1280_plis_amber_lightteak.webp",
          "/Fan/emperion_magna_1280_plis_amber_lightteak.webp",
        ],
        price: 17999,
        originalPrice: 25999,
        stock: 14,
      },
      {
        name: "Pearl White",
        hex: "#f5f5f4",
        images: [
          "/Fan/emperion_magna_1280_plis_pearl_white.webp",
          "/Fan/emperion_magna_1280_plis_pearl_white.webp",
        ],
        price: 16999,
        originalPrice: 24999,
        stock: 9,
      },
      {
        name: "Lava Grey",
        hex: "#4a4a4a",
        images: [
          "/Fan/emperion_magna_plis_1280_lava_grey-01.webp",
          "/Fan/emperion_magna_plis_1280_lava_grey-01.webp",
        ],
        price: 16999,
        originalPrice: 24999,
        stock: 5,
      },
    ],
    description:
      "Energy-efficient BLDC ceiling fan with remote control, delivering superior air delivery and silent operation.",
    features: [
      "1200mm sweep size",
      "Remote control operation",
      "350 RPM motor speed",
      "Double ball bearing",
      "2-year warranty",
    ],
    specifications: {
      "Sweep Size (mm)": "1200mm",
      "Power Consumption (Watts)": "28W",
      "Air Delivery (CMM)": "230 CMM",
      RPM: "350",
      "Number of Blades": "3",
      Voltage: "220-240V",
      Frequency: "50Hz",
      "Motor Type": "BLDC Motor",
      Warranty: "2 Years",
      Color: "Amberlight Teak / Pearl White / Lava Grey",
    },
  },
  {
    id: 27,
    name: "Emperion Linea",
    category: "Fans",
    categoryId: "fans",
    brand: "Atomberg",
    tag: "Featured",
    price: 17999,
    originalPrice: 25999,
    discount: 22,
    stock: 72,
    rating: 4.5,
    reviews: 654,
    image: "/Fan/Emperio_linea_1250_Antique_goldleaf.webp",
    badge: "Featured",
    colors: [
      {
        name: "Antique Goldleaf",
        hex: "#f5f5f4",
        images: [
          "/Fan/Emperio_linea_1250_Antique_goldleaf.webp",
          "/Fan/Emperio_linea_1250_Antique_goldleaf.webp",
        ],
        price: 17999,
        originalPrice: 25999,
        stock: 40,
      },
      {
        name: "Pearl White",
        hex: "#2c5f8a",
        images: [
          "/Fan/Emperio_linea_1250_pearlwhite.webp",
          "/Fan/Emperio_linea_1250_pearlwhite.webp",
        ],
        price: 16999,
        originalPrice: 24999,
        stock: 32,
      },
      {
        name: "Lava Grey",
        hex: "#2c5f8a",
        images: [
          "/Fan/Emperio_linea_1250_lava_grey.webp",
          "/Fan/Emperio_linea_1250_lava_grey.webp",
        ],
        price: 16999,
        originalPrice: 24999,
        stock: 32,
      },
    ],
    description:
      "Powerful high-speed table fan with a rust-proof body, ideal for home and office use.",
    features: [
      "400mm blade sweep",
      "3-speed control",
      "Rust-proof powder coating",
      "High air thrust motor",
      "2-year warranty",
    ],
    specifications: {
      "Sweep Size (mm)": "400mm",
      "Power Consumption (Watts)": "55W",
      "Air Delivery (CMM)": "60 CMM",
      RPM: "2300",
      "Number of Blades": "3",
      Voltage: "220-240V",
      Frequency: "50Hz",
      "Motor Type": "Induction Motor",
      Warranty: "2 Years",
      Color: "White / Blue",
    },
  },
  {
    id: 28,
    name: "Renesa Elite",
    category: "Fans",
    categoryId: "fans",
    brand: "Atomberg",
    tag: "New Arrival",
    price: 5699,
    originalPrice: 9600,
    discount: 24,
    stock: 58,
    rating: 4.4,
    reviews: 421,
    image: "/Fan/renesa_elite_dark_walnut-1400.webp",
    badge: "New",
    colors: [
      {
        name: "Dark Walnut",
        hex: "#f0e6d2",
        images: [
          "/Fan/renesa_elite_dark_walnut-1400.webp",
          "/Fan/renesa_elite_dark_walnut-1400.webp",
        ],
        price: 5699,
        originalPrice: 9600,
        stock: 30,
      },
      {
        name: "Golden Oakwood ",
        hex: "#5c3a21",
        images: [
          "/Fan/renesa_elite_golden_oakwood-1400.webp",
          "/Fan/renesa_elite_golden_oakwood-1400.webp",
        ],
        price: 5699,
        originalPrice: 9600,
        stock: 18,
      },
      {
        name: "Ritz Blue",
        hex: "#1c1c1c",
        images: [
          "/Fan/renesa_elite_ritz_blue-1400.webp",
          "/Fan/renesa_elite_ritz_blue-1400.webp",
        ],
        price: 5199,
        originalPrice: 8700,
        stock: 10,
        specifications: {
          Warranty: "3 Years",
        },
      },
      {
        name: "Sand Grey",
        hex: "#1c1c1c",
        images: [
          "/Fan/renesa_elite_sand_grey-1400.webp",
          "/Fan/renesa_elite_sand_grey-1400.webp",
        ],
        price: 5199,
        originalPrice: 8700,
        stock: 10,
        specifications: {
          Warranty: "3 Years",
        },
      },
    ],
    description:
      "Anti-dust coated ceiling fan with a decorative finish, built for strong air delivery and easy maintenance.",
    features: [
      "1200mm sweep size",
      "Anti-dust powder coating",
      "High air delivery",
      "Double ball bearing",
      "2-year warranty",
    ],
    specifications: {
      "Sweep Size (mm)": "1200mm",
      "Power Consumption (Watts)": "75W",
      "Air Delivery (CMM)": "210 CMM",
      RPM: "380",
      "Number of Blades": "3",
      Voltage: "220-240V",
      Frequency: "50Hz",
      "Motor Type": "Induction Motor",
      Warranty: "2 Years",
      Color: "Ivory / Brown / Black",
    },
  },
  {
    id: 29,
    name: "Aris Illusia ",
    category: "Fans",
    categoryId: "fans",
    brand: "Atomberg",
    tag: "New Arrival",
    price: 9999,
    originalPrice: 16960,
    discount: 24,
    stock: 58,
    rating: 4.4,
    reviews: 421,
    image: "/Fan/arisllusia_1250_glacierblue.webp",
    badge: "New",
    colors: [
      {
        name: "Glacier Blue",
        hex: "#f0e6d2",
        images: [
          "/Fan/arisllusia_1250_glacierblue.webp",
          "/Fan/arisllusia_1250_glacierblue.webp",
        ],
        price: 9999,
        originalPrice: 16960,
        stock: 30,
      },
      {
        name: "Pearl White",
        hex: "#5c3a21",
        images: [
          "/Fan/arisllusia_1250_pearlwhite.webp",
          "/Fan/arisllusia_1250_pearlwhite.webp",
        ],
        price: 5699,
        originalPrice: 9600,
        stock: 18,
      },
      {
        name: "Rose Gold",
        hex: "#1c1c1c",
        images: [
          "/Fan/arisllusia_1250_rosegold.webp",
          "/Fan/arisllusia_1250_rosegold.webp",
        ],
        price: 5199,
        originalPrice: 8700,
        stock: 10,
        specifications: {
          Warranty: "3 Years",
        },
      },
      {
        name: "Sand Grey",
        hex: "#1c1c1c",
        images: [
          "/Fan/renesa_elite_sand_grey-1400.webp",
          "/Fan/renesa_elite_sand_grey-1400.webp",
        ],
        price: 5199,
        originalPrice: 8700,
        stock: 10,
        specifications: {
          Warranty: "3 Years",
        },
      },
    ],
    description:
      "Anti-dust coated ceiling fan with a decorative finish, built for strong air delivery and easy maintenance.",
    features: [
      "1200mm sweep size",
      "Anti-dust powder coating",
      "High air delivery",
      "Double ball bearing",
      "2-year warranty",
    ],
    specifications: {
      "Sweep Size (mm)": "1200mm",
      "Power Consumption (Watts)": "75W",
      "Air Delivery (CMM)": "210 CMM",
      RPM: "380",
      "Number of Blades": "3",
      Voltage: "220-240V",
      Frequency: "50Hz",
      "Motor Type": "Induction Motor",
      Warranty: "2 Years",
      Color: "Ivory / Brown / Black",
    },
  },
];

export const PRODUCTS = RAW_PRODUCTS.map((product) => ({
  ...product,
  slug: slugify(product.name),
}));

// Derived from the actual product data (instead of a hand-maintained list)
// so a brand filter chip only ever appears when products for it exist.
export const BRANDS = [...new Set(RAW_PRODUCTS.map((product) => product.brand))].sort();

export function getProductBySlug(slug) {
  return PRODUCTS.find((product) => product.slug === slug);
}
