export const PRODUCTS = [
  {
    id: 1,
    name: "Anchor 20A Modular Switch with LED Indicator",
    category: "Switches & Sockets",
    tag: "Best Seller",
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    rating: 4.8,
    reviews: 2345,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "Anchor",
    description:
      "Premium quality modular switch with LED indicator, designed for durability and safety in modern homes.",
    features: [
      "20A current rating",
      "LED indicator light",
      "Fire-resistant polycarbonate body",
      "Easy snap-fit installation",
      "5-year warranty",
    ],
  },
  {
    id: 2,
    name: "Polycab 1.5mm 90m FR House Wire (Red)",
    category: "Wires & Cables",
    tag: "New Arrival",
    price: 24.99,
    originalPrice: 32.99,
    discount: 24,
    rating: 4.9,
    reviews: 1823,
    image: "/images/product1.webp",
    badge: "New",
    badgeType: "new-arrivals",
    brand: "Polycab",
    description:
      "Flame retardant house wire ideal for residential and commercial wiring, ensuring maximum safety.",
    features: [
      "1.5 sq mm thickness",
      "90 meters length",
      "Flame retardant (FR) grade",
      "High conductivity copper",
      "ISI marked",
    ],
  },
  {
    id: 3,
    name: "Havells 1200mm Ceiling Fan with Remote Control",
    category: "Fans",
    tag: "Popular",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    rating: 4.7,
    reviews: 892,
    image: "/images/product1.webp",
    badge: "Popular",
    badgeType: "popular",
    brand: "Havells",
    description:
      "Energy-efficient ceiling fan with remote control, delivering superior air delivery and silent operation.",
    features: [
      "1200mm sweep size",
      "Remote control operation",
      "350 RPM motor speed",
      "Double ball bearing",
      "5-star energy rating",
    ],
  },
  {
    id: 4,
    name: "RR Kabel 6A 3-Pin Universal Socket",
    category: "Switches & Sockets",
    tag: "Featured",
    price: 8.49,
    originalPrice: 11.99,
    discount: 29,
    rating: 4.6,
    reviews: 1567,
    image: "/images/product1.webp",
    badge: "Featured",
    badgeType: "featured",
    brand: "RR Kabel",
    description:
      "Universal 3-pin socket with safety shutter, perfect for all standard plug types in home and office.",
    features: [
      "6A rating",
      "Universal compatibility",
      "Safety shutter mechanism",
      "UV resistant body",
      "Easy installation",
    ],
  },
  {
    id: 5,
    name: "KEI 4mm 4-Core Armoured Copper Cable",
    category: "Wires & Cables",
    tag: "Best Seller",
    price: 45.99,
    originalPrice: 58.99,
    discount: 22,
    rating: 4.5,
    reviews: 3210,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "KEI",
    description:
      "Heavy-duty armoured cable for industrial and outdoor applications, providing excellent protection.",
    features: [
      "4 sq mm thickness",
      "4-core copper conductor",
      "Steel wire armoured",
      "UV & moisture resistant",
      "ISI & ISO certified",
    ],
  },
  {
    id: 6,
    name: "Finolex 25A DP MCB Switch",
    category: "Circuit Protection",
    tag: "New Arrival",
    price: 15.99,
    originalPrice: 19.99,
    discount: 20,
    rating: 4.8,
    reviews: 654,
    image: "/images/product1.webp",
    badge: "New",
    badgeType: "new-arrivals",
    brand: "Finolex",
    description:
      "Double pole miniature circuit breaker providing overload and short circuit protection for electrical circuits.",
    features: [
      "25A current rating",
      "Double pole (DP)",
      "C curve tripping",
      "10kA breaking capacity",
      "DIN rail mounting",
    ],
  },
  {
    id: 7,
    name: "Philips 9W LED Bulb (Cool Day Light)",
    category: "Lighting",
    tag: "Best Seller",
    price: 6.99,
    originalPrice: 9.99,
    discount: 30,
    rating: 4.7,
    reviews: 4521,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "Philips",
    description:
      "Energy-saving LED bulb with cool daylight color, perfect for home and office lighting needs.",
    features: [
      "9W power consumption",
      "6500K cool daylight",
      "900 lumens brightness",
      "25,000 hours lifespan",
      "BIS certified",
    ],
  },
  {
    id: 8,
    name: "Crompton 25L Storage Water Heater",
    category: "Water Heaters",
    tag: "Popular",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    rating: 4.6,
    reviews: 1876,
    image: "/images/product1.webp",
    badge: "Popular",
    badgeType: "popular",
    brand: "Crompton",
    description:
      "High-capacity storage water heater with advanced safety features and energy-efficient heating.",
    features: [
      "25 liters capacity",
      "3KW heating element",
      "Multi-function safety valve",
      "PUF insulation",
      "5-year tank warranty",
    ],
  },
  {
    id: 9,
    name: "Bajaj 1200W Dry Iron with Non-Stick Plate",
    category: "Irons",
    tag: "Featured",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.5,
    reviews: 2341,
    image: "/images/product1.webp",
    badge: "Featured",
    badgeType: "featured",
    brand: "Bajaj",
    description:
      "Powerful dry iron with non-stick soleplate for smooth gliding and efficient wrinkle removal.",
    features: [
      "1200W power",
      "Non-stick soleplate",
      "Temperature control dial",
      "360° swivel cord",
      "Lightweight design",
    ],
  },
  {
    id: 10,
    name: "Orient 1400mm BLDC Ceiling Fan with Remote",
    category: "Fans",
    tag: "New Arrival",
    price: 109.99,
    originalPrice: 139.99,
    discount: 21,
    rating: 4.8,
    reviews: 987,
    image: "/images/product1.webp",
    badge: "New",
    badgeType: "new-arrivals",
    brand: "Orient",
    description:
      "Brushless DC motor ceiling fan with remote control, offering 50% energy savings and whisper-quiet operation.",
    features: [
      "1400mm sweep size",
      "BLDC motor technology",
      "Remote control with timer",
      "50% energy saving",
      "5-star BEE rating",
    ],
  },
  {
    id: 11,
    name: "Legrand 16A Modular Power Socket",
    category: "Switches & Sockets",
    tag: "Best Seller",
    price: 14.99,
    originalPrice: 18.99,
    discount: 21,
    rating: 4.9,
    reviews: 1654,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "Legrand",
    description:
      "High-current modular socket ideal for heavy-duty appliances like AC, geyser, and microwave.",
    features: [
      "16A high current rating",
      "Shatter-proof polycarbonate",
      "Spring-loaded shutter",
      "Anti-weld silver contacts",
      "10-year warranty",
    ],
  },
  {
    id: 12,
    name: "Schneider 32A 4-Pole MCB",
    category: "Circuit Protection",
    tag: "Popular",
    price: 35.99,
    originalPrice: 45.99,
    discount: 22,
    rating: 4.7,
    reviews: 743,
    image: "/images/product1.webp",
    badge: "Popular",
    badgeType: "popular",
    brand: "Schneider",
    description:
      "Four-pole MCB for three-phase circuits, providing reliable protection against overload and short circuit.",
    features: [
      "32A current rating",
      "4-pole configuration",
      "C curve characteristics",
      "10kA breaking capacity",
      "IEC certified",
    ],
  },
  {
    id: 13,
    name: "L&T 40A 4-Pole RCCB/ELCB",
    category: "Circuit Protection",
    tag: "Featured",
    price: 55.99,
    originalPrice: 69.99,
    discount: 20,
    rating: 4.8,
    reviews: 532,
    image: "/images/product1.webp",
    badge: "Featured",
    badgeType: "featured",
    brand: "L&T",
    description:
      "Residual current circuit breaker providing earth leakage protection for electrical circuits and equipment.",
    features: [
      "40A rated current",
      "30mA sensitivity",
      "4-pole configuration",
      "Fast tripping mechanism",
      "ISI marked",
    ],
  },
  {
    id: 14,
    name: "Wipro 15W LED Panel Light (Round)",
    category: "Lighting",
    tag: "New Arrival",
    price: 19.99,
    originalPrice: 24.99,
    discount: 20,
    rating: 4.6,
    reviews: 1876,
    image: "/images/product1.webp",
    badge: "New",
    badgeType: "new-arrivals",
    brand: "Wipro",
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "15W power consumption",
      "6500K cool white light",
      "1500 lumens brightness",
      "Surface/recess mounting",
      "3-year warranty",
    ],
  },
  {
    id: 15,
    name: "V-Guard 1.5 Ton Inverter Split AC Stabilizer",
    category: "Appliances",
    tag: "Best Seller",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    rating: 4.7,
    reviews: 4321,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "V-Guard",
    description:
      "Advanced voltage stabilizer for inverter ACs, ensuring stable power supply and protection.",
    features: [
      "For 1.5 ton inverter AC",
      "Working range: 130V-300V",
      "Smart i-start technology",
      "High/low voltage cutoff",
      "Wall mountable design",
    ],
  },
  {
    id: 16,
    name: "McCoy 16A 5-Pin Industrial Socket",
    category: "Switches & Sockets",
    tag: "Popular",
    price: 11.99,
    originalPrice: 14.99,
    discount: 20,
    rating: 4.5,
    reviews: 876,
    image: "/images/product1.webp",
    badge: "Popular",
    badgeType: "popular",
    brand: "McCoy",
    description:
      "Heavy-duty industrial socket with 5-pin configuration for three-phase equipment connections.",
    features: [
      "16A rating",
      "5-pin (3P+N+E)",
      "IP44 splash proof",
      "Industrial grade body",
      "Screwless terminal",
    ],
  },
  {
    id: 17,
    name: "Hager 63A 4-Pole Changeover Switch",
    category: "Circuit Protection",
    tag: "Featured",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    rating: 4.8,
    reviews: 432,
    image: "/images/product1.webp",
    badge: "Featured",
    badgeType: "featured",
    brand: "Hager",
    description:
      "Manual changeover switch for generator and mains power source switching in residential and commercial setups.",
    features: [
      "63A rated current",
      "4-pole configuration",
      "Compact design",
      "Easy manual operation",
      "IEC & ISI certified",
    ],
  },
  {
    id: 18,
    name: "Polycab 2.5mm 3-Core Flat Submersible Cable",
    category: "Wires & Cables",
    tag: "Best Seller",
    price: 38.99,
    originalPrice: 48.99,
    discount: 20,
    rating: 4.7,
    reviews: 1234,
    image: "/images/product1.webp",
    badge: "Best Seller",
    badgeType: "best-sellers",
    brand: "Polycab",
    description:
      "Flat submersible cable designed for borewell pumps, providing reliable power supply underwater.",
    features: [
      "2.5 sq mm thickness",
      "3-core configuration",
      "PVC insulated",
      "Water resistant",
      "ISI marked",
    ],
  },
];

export function getProductById(id) {
  return PRODUCTS.find((product) => String(product.id) === String(id));
}

export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "switches-sockets", label: "Switches & Sockets" },
  { id: "wires-cables", label: "Wires & Cables" },
  { id: "fans", label: "Fans" },
  { id: "circuit-protection", label: "Circuit Protection" },
  { id: "lighting", label: "Lighting" },
  { id: "water-heaters", label: "Water Heaters" },
  { id: "irons", label: "Irons" },
  { id: "appliances", label: "Appliances" },
];

export const BRANDS = [
  "Anchor",
  "Polycab",
  "Havells",
  "RR Kabel",
  "KEI",
  "Finolex",
  "Philips",
  "Crompton",
  "Bajaj",
  "Orient",
  "Legrand",
  "Schneider",
  "L&T",
  "Wipro",
  "V-Guard",
  "McCoy",
  "Hager",
];
