export function slugify(value) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const CATEGORIES = [
  { id: "all", label: "All Products", icon: "HiSquares2X2" },
  {
    id: "switches-accessories",
    label: "Switches & Accessories",
    icon: "HiAdjustmentsHorizontal",
  },
  {
    id: "electrical-wires-cables",
    label: "Electrical Wires & Cables",
    icon: "HiBolt",
  },
  { id: "mcbs-protection", label: "MCBs & Protection", icon: "HiShieldCheck" },
  { id: "lighting", label: "Lighting", icon: "HiLightBulb" },
  { id: "fans", label: "Fans", icon: "HiArrowPath" },
  { id: "water-pumps-heaters", label: "Water Pumps & Heaters", icon: "HiFire" },
  { id: "pipes-fittings", label: "Pipes and Fittings", icon: "HiCube" },
  {
    id: "industrial-electrical-products",
    label: "Industrial Electrical Products",
    icon: "HiBuildingOffice2",
  },
  {
    id: "electrical-tools-accessories",
    label: "Electrical Tools & Accessories",
    icon: "HiWrenchScrewdriver",
  },
  {
    id: "earthing-materials",
    label: "Earthing Materials",
    icon: "HiGlobeAlt",
  },
  {
    id: "home-appliance",
    label: "Home Appliance",
    icon: "HiHome",
  },
  {
    id: "aquagard",
    label: "Aquagard",
    icon: "HiBeaker",
  },
];

export const BRANDS = [
  "Anchor",
  "Polycab",
  "Havells",
  "RR Kabel",
  "KEI",
  "Finolex",
  "Philips",
  "Jaguar",
  "Crompton",
  "Bajaj",
  "Orient",
  "Atomberg",
  "Usha",
  "Kuhl",
  "McCoy",
  "V-Guard",
  "Lister",
  "Legrand",
];

const RAW_PRODUCTS = [
  // Switches & Accessories
  {
    id: 1,
    name: "Anchor Roma 20A Modular Switch with LED Indicator",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Anchor",
    tag: "Best Seller",
    price: 249,
    originalPrice: 329,
    discount: 24,
    stock: 140,
    rating: 4.8,
    reviews: 2345,
    image: "/images/productimages/2.png",
    badge: "Best Seller",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/images/productimages/2.png", "/images/productimages/2.png"],
        stock: 140,
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/images/productimages/2.png", "/images/productimages/2.png"],
        price: 269,
        originalPrice: 349,
        stock: 6,
      },
      {
        name: "Black",
        hex: "#1c1c1c",
        // DEMO STAND-IN: not the real Black photo, same reason as above.
        images: ["/images/productimages/2.png", "/images/productimages/2.png"],
        price: 279,
        originalPrice: 359,
        stock: 2,
      },
    ],
    description:
      "Premium quality modular switch with LED indicator, designed for durability and safety in modern homes.",
    features: [
      "20A current rating",
      "LED indicator light",
      "Fire-resistant polycarbonate body",
      "Easy snap-fit installation",
      "5-year warranty",
    ],
  },
  {
    id: 2,
    name: "Legrand Mylinc 6A One Way Switch",
    category: "Switches & Accessories",
    categoryId: "switches-accessories",
    brand: "Legrand",
    tag: "Featured",
    price: 89,
    originalPrice: 119,
    discount: 25,
    stock: 320,
    rating: 4.7,
    reviews: 1432,
    image: "/images/productimages/3.webp",
    badge: "Featured",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/images/productimages/3.webp"],
      },
      {
        name: "Ivory",
        hex: "#f0e6d2",
        images: ["/images/productimages/3.webp"],
      },
    ],
    description:
      "Sleek one-way switch with a soft-touch rocker action, built to the highest French design standards.",
    features: [
      "6A current rating",
      "Soft-touch rocker action",
      "Anti-bacterial finish",
      "Concealed screw design",
      "10-year warranty",
    ],
  },

  // Electrical Wires & Cables
  {
    id: 3,
    name: "Polycab 1.5 sq mm FR PVC Insulated House Wire (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "Polycab",
    tag: "New Arrival",
    price: 1899,
    originalPrice: 2399,
    discount: 21,
    stock: 54,
    rating: 4.9,
    reviews: 1823,
    image: "/images/productimages/p.jpg",
    badge: "New",
    colors: [
      { name: "Red", hex: "#c0392b", images: ["/images/productimages/p.jpg"] },
      { name: "Blue", hex: "#2c5f8a", images: ["/images/productimages/p.jpg"] },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: ["/images/productimages/p.jpg"],
      },
    ],
    description:
      "Flame retardant house wire ideal for residential and commercial wiring, ensuring maximum safety.",
    features: [
      "1.5 sq mm thickness",
      "90 meters length",
      "Flame retardant (FR) grade",
      "High conductivity copper",
      "ISI marked",
    ],
  },
  {
    id: 4,
    name: "RR Kabel 2.5 sq mm Silicon FR Multistrand Cable (90m)",
    category: "Electrical Wires & Cables",
    categoryId: "electrical-wires-cables",
    brand: "RR Kabel",
    tag: "Best Seller",
    price: 2799,
    originalPrice: 3499,
    discount: 20,
    stock: 38,
    rating: 4.6,
    reviews: 1567,
    image: "/images/productimages/p1.png",
    badge: "Best Seller",
    colors: [
      { name: "Red", hex: "#c0392b", images: ["/images/productimages/p1.png"] },
      {
        name: "Black",
        hex: "#1c1c1c",
        images: ["/images/productimages/p1.png"],
      },
    ],
    description:
      "Multistrand FR-LSH cable with silicon-treated insulation for higher fire and heat resistance.",
    features: [
      "2.5 sq mm thickness",
      "90 meters length",
      "Silicon FR-LSH insulation",
      "High flexibility multistrand copper",
      "ISI marked",
    ],
  },

  // MCBs & Protection
  {
    id: 5,
    name: "Havells 32A Double Pole MCB",
    category: "MCBs & Protection",
    categoryId: "mcbs-protection",
    brand: "Havells",
    tag: "Popular",
    price: 349,
    originalPrice: 449,
    discount: 22,
    stock: 210,
    rating: 4.7,
    reviews: 892,
    image: "/images/productimages/p3.jpg",
    badge: "Popular",
    description:
      "Double pole miniature circuit breaker providing reliable overload and short circuit protection.",
    features: [
      "32A current rating",
      "Double pole (DP)",
      "C curve tripping",
      "10kA breaking capacity",
      "DIN rail mounting",
    ],
  },
  {
    id: 6,
    name: "KEI 40A 4-Pole RCCB/ELCB",
    category: "MCBs & Protection",
    categoryId: "mcbs-protection",
    brand: "KEI",
    tag: "Featured",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    stock: 65,
    rating: 4.8,
    reviews: 532,
    image: "/images/productimages/p4.webp",
    badge: "Featured",
    description:
      "Residual current circuit breaker providing earth leakage protection for entire electrical circuits.",
    features: [
      "40A rated current",
      "30mA sensitivity",
      "4-pole configuration",
      "Fast tripping mechanism",
      "ISI marked",
    ],
  },

  // Lighting
  {
    id: 7,
    name: "Philips 12W LED Bulb (Cool Day Light, Pack of 2)",
    category: "Lighting",
    categoryId: "lighting",
    brand: "Philips",
    tag: "Best Seller",
    price: 249,
    originalPrice: 349,
    discount: 29,
    stock: 480,
    rating: 4.7,
    reviews: 4521,
    image: "/images/productimages/7.webp",
    badge: "Best Seller",
    colors: [
      {
        name: "Cool Daylight",
        hex: "#eef3ff",
        images: ["/images/productimages/7.webp"],
      },
      {
        name: "Warm White",
        hex: "#ffe6b3",
        images: ["/images/productimages/7.webp"],
      },
    ],
    description:
      "Energy-saving LED bulb twin pack with cool daylight color, perfect for home and office lighting.",
    features: [
      "12W power consumption",
      "6500K cool daylight",
      "1200 lumens brightness",
      "25,000 hours lifespan",
      "BIS certified",
    ],
  },
  {
    id: 8,
    name: "Crompton 18W Round LED Panel Light",
    category: "Lighting",
    categoryId: "lighting",
    brand: "Crompton",
    tag: "New Arrival",
    price: 399,
    originalPrice: 549,
    discount: 27,
    stock: 96,
    rating: 4.6,
    reviews: 1876,
    image: "/images/productimages/8.jpg",
    badge: "New",
    colors: [
      {
        name: "Cool White",
        hex: "#eef3ff",
        images: ["/images/productimages/8.jpg"],
      },
      {
        name: "Warm White",
        hex: "#ffe6b3",
        images: ["/images/productimages/8.jpg"],
      },
    ],
    description:
      "Sleek round LED panel light delivering uniform illumination, perfect for modern false ceilings.",
    features: [
      "18W power consumption",
      "6500K cool white light",
      "1800 lumens brightness",
      "Surface/recess mounting",
      "3-year warranty",
    ],
  },

  // Fans
  {
    id: 9,
    name: "Atomberg Emperion Magna",
    category: "Fans",
    categoryId: "fans",
    brand: "Atomberg",
    tag: "Popular",
    price: 17999,
    originalPrice: 25999,
    discount: 23,
    stock: 14,
    rating: 4.7,
    reviews: 987,
    image: "/images/productimages/atomeberg.jpg",
    badge: "Popular",
    colors: [
      {
        name: "Amberlight Teak",
        hex: "#f5f5f4",
        images: ["/images/productimages/atomeberg.jpg"],
        price: 17999,
        originalPrice: 25999,
      },
      {
        name: "Pearl White",
        hex: "#6b4426",
        images: ["/images/productimages/atombergwhite.jpg"],
        price: 16999,
        originalPrice: 24999,
      },
      {
        name: "Lava Grey",
        hex: "#f0e6d2",
        images: ["/images/productimages/9.jpg"],
        price: 16999,
        originalPrice: 24999,
      },
    ],
    description:
      "Energy-efficient ceiling fan with remote control, delivering superior air delivery and silent operation.",
    features: [
      "1280",
      "Remote control operation",
      "350 RPM motor speed",
      "Double ball bearing",
      "2-year warranty",
    ],
  },
  {
    id: 10,
    name: "Emperion Linea",
    category: "Fans",
    categoryId: "fans",
    brand: "Usha",
    tag: "Featured",
    price: 17999,
    originalPrice: 25999,
    discount: 22,
    stock: 72,
    rating: 4.5,
    reviews: 654,
    image: "/images/productimages/10.jpg",
    badge: "Featured",
    colors: [
      {
        name: "Antique Gold Leaf",
        hex: "#f5f5f4",
        images: ["/images/productimages/10.jpg"],
        price: 17999,
        originalPrice: 25999,
      },
      {
        name: "Pearl White, Lava Grey",
        hex: "#2c5f8a",
        images: ["/images/productimages/10.jpg"],
        price: 16999,
        originalPrice: 24999,
      },
    ],
    description:
      "Powerful high-speed table fan with a rust-proof body, ideal for home and office use.",
    features: [
      "400mm blade sweep",
      "3-speed control",
      "Rust-proof powder coating",
      "High air thrust motor",
      "2-year warranty",
    ],
  },

  // Water Pumps & Heaters
  {
    id: 11,
    name: "V-Guard 15L Instant Water Heater",
    category: "Water Pumps & Heaters",
    categoryId: "water-pumps-heaters",
    brand: "V-Guard",
    tag: "Best Seller",
    price: 5499,
    originalPrice: 6999,
    discount: 21,
    stock: 41,
    rating: 4.6,
    reviews: 1234,
    image: "/images/productimages/11.webp",
    badge: "Best Seller",
    description:
      "High-capacity storage water heater with advanced safety features and energy-efficient heating.",
    features: [
      "15 liters capacity",
      "2KW heating element",
      "Multi-function safety valve",
      "PUF insulation",
      "5-year tank warranty",
    ],
  },
  {
    id: 12,
    name: "Lister 0.5HP Single Phase Water Pump",
    category: "Water Pumps & Heaters",
    categoryId: "water-pumps-heaters",
    brand: "Lister",
    tag: "New Arrival",
    price: 3299,
    originalPrice: 4199,
    discount: 21,
    stock: 27,
    rating: 4.5,
    reviews: 421,
    image: "/images/productimages/12.webp",
    badge: "New",
    description:
      "Compact single phase water pump built for reliable domestic water supply with low maintenance.",
    features: [
      "0.5HP motor power",
      "Single phase operation",
      "Corrosion-resistant casing",
      "Thermal overload protector",
      "1-year warranty",
    ],
  },

  // Pipes and Fittings
  {
    id: 13,
    name: "Finolex 4-inch PVC Pipe (3m Length)",
    category: "Pipes and Fittings",
    categoryId: "pipes-fittings",
    brand: "Finolex",
    tag: "Popular",
    price: 899,
    originalPrice: 1099,
    discount: 18,
    stock: 115,
    rating: 4.7,
    reviews: 743,
    image: "/images/productimages/13.webp",
    badge: "Popular",
    description:
      "Heavy-duty PVC pipe suited for plumbing and drainage applications with long-lasting durability.",
    features: [
      "4-inch diameter",
      "3 meter length",
      "UV stabilized PVC",
      "High pressure resistance",
      "ISI marked",
    ],
  },
  {
    id: 14,
    name: "Jaguar Continental Series Basin Mixer Tap",
    category: "Pipes and Fittings",
    categoryId: "pipes-fittings",
    brand: "Jaguar",
    tag: "Featured",
    price: 3499,
    originalPrice: 4499,
    discount: 22,
    stock: 19,
    rating: 4.8,
    reviews: 356,
    image: "/images/productimages/14.jpg",
    badge: "Featured",
    colors: [
      {
        name: "Chrome",
        hex: "#c9ccd1",
        images: ["/images/productimages/14.jpg"],
      },
      {
        name: "Matte Black",
        hex: "#1c1c1c",
        images: ["/images/productimages/14.jpg"],
      },
    ],
    description:
      "Premium chrome-finish basin mixer tap combining elegant design with a smooth, drip-free flow.",
    features: [
      "Solid brass construction",
      "Mirror chrome finish",
      "360° swivel spout",
      "Ceramic disc cartridge",
      "7-year warranty",
    ],
  },

  // Industrial Electrical Products
  {
    id: 15,
    name: "McCoy 32A 5-Pin Industrial Socket",
    category: "Industrial Electrical Products",
    categoryId: "industrial-electrical-products",
    brand: "McCoy",
    tag: "Best Seller",
    price: 649,
    originalPrice: 799,
    discount: 19,
    stock: 88,
    rating: 4.5,
    reviews: 876,
    image: "/images/productimages/15.png",
    badge: "Best Seller",
    description:
      "Heavy-duty industrial socket with 5-pin configuration for three-phase equipment connections.",
    features: [
      "32A rating",
      "5-pin (3P+N+E)",
      "IP44 splash proof",
      "Industrial grade body",
      "Screwless terminal",
    ],
  },
  {
    id: 16,
    name: "Atomberg Renesa+ BLDC Exhaust Fan (Industrial Grade)",
    category: "Industrial Electrical Products",
    categoryId: "industrial-electrical-products",
    brand: "Atomberg",
    tag: "New Arrival",
    price: 2199,
    originalPrice: 2799,
    discount: 21,
    stock: 33,
    rating: 4.8,
    reviews: 612,
    image: "/images/productimages/16.jpg",
    badge: "New",
    colors: [
      {
        name: "White",
        hex: "#f5f5f4",
        images: ["/images/productimages/16.jpg"],
      },
      {
        name: "Grey",
        hex: "#9aa0a6",
        images: ["/images/productimages/16.jpg"],
      },
    ],
    description:
      "Brushless DC motor exhaust fan built for heavy-duty ventilation with up to 65% energy savings.",
    features: [
      "BLDC motor technology",
      "High air displacement",
      "65% energy saving",
      "Rust-proof body",
      "2-year warranty",
    ],
  },

  // Electrical Tools & Accessories
  {
    id: 17,
    name: "Bajaj Majesty Digital Multimeter",
    category: "Electrical Tools & Accessories",
    categoryId: "electrical-tools-accessories",
    brand: "Bajaj",
    tag: "Popular",
    price: 799,
    originalPrice: 999,
    discount: 20,
    stock: 156,
    rating: 4.6,
    reviews: 543,
    image: "/images/productimages/17.jpg",
    badge: "Popular",
    description:
      "Reliable digital multimeter for measuring voltage, current and resistance on the go.",
    features: [
      "AC/DC voltage testing",
      "Auto-ranging display",
      "Continuity buzzer",
      "Overload protection",
      "1-year warranty",
    ],
  },
  {
    id: 18,
    name: "Kuhl Precision Wire Stripper & Cutter Tool Kit",
    category: "Electrical Tools & Accessories",
    categoryId: "electrical-tools-accessories",
    brand: "Kuhl",
    tag: "Featured",
    price: 549,
    originalPrice: 699,
    discount: 21,
    stock: 60,
    rating: 4.4,
    reviews: 298,
    image: "/images/productimages/18.jpeg",
    badge: "Featured",
    description:
      "Precision-ground wire stripper and cutter kit for fast, clean electrical wiring work.",
    features: [
      "Hardened steel jaws",
      "Self-adjusting stripping",
      "Non-slip ergonomic grip",
      "Insulated up to 1000V",
      "1-year warranty",
    ],
  },

  // Earthing Materials
  // Add your Earthing Materials products here.
  // Example shape — copy this object, edit the values, keep categoryId as "earthing-materials":
  // {
  //   id: 19,
  //   name: "Product Name",
  //   category: "Earthing Materials",
  //   categoryId: "earthing-materials",
  //   brand: "Anchor",
  //   tag: "New Arrival",
  //   price: 0,
  //   originalPrice: 0,
  //   discount: 0,
  //   rating: 4.5,
  //   reviews: 0,
  //   image: "/images/productimages/REPLACE.jpg",
  //   badge: "New",
  //   colors: [{ name: "Color Name", hex: "#000000", images: ["/images/productimages/REPLACE.jpg"] }],
  //   description: "",
  //   features: [],
  // },

  // Home Appliance
  // Add your Home Appliance products here, categoryId: "home-appliance".

  // Aquagard
  // Add your Aquagard products here, categoryId: "aquagard".
];

export const PRODUCTS = RAW_PRODUCTS.map((product) => ({
  ...product,
  slug: slugify(product.name),
}));

export function getProductBySlug(slug) {
  return PRODUCTS.find((product) => product.slug === slug);
}
